#!/usr/bin/env bash
# reset.sh — Exercise 0E-03: Modify, Plan, Apply, Destroy
# Creates a working Terraform config with initial state already applied

WORK_DIR="/tmp/devops-lab/0E-03"

echo "Resetting exercise 0E-03..."

# Detect terraform/tofu
TF_CMD=""
if command -v tofu &>/dev/null; then TF_CMD="tofu"
elif command -v terraform &>/dev/null; then TF_CMD="terraform"
fi

# Clean up previous run
rm -rf "$WORK_DIR"
mkdir -p "$WORK_DIR/output"

# Write main.tf (starting state — 2 resources, environment=dev)
cat > "$WORK_DIR/main.tf" << 'EOF'
terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
  }
}

# AWS equivalent:
# provider "aws" { region = var.aws_region }

resource "local_file" "config_json" {
  filename = "/tmp/devops-lab/0E-03/output/config.json"
  content  = "{\"project\": \"${var.project_name}\", \"env\": \"${var.environment}\"}"
}

# AWS equivalent:
# resource "aws_s3_object" "config_json" {
#   bucket  = aws_s3_bucket.configs.id
#   key     = "config.json"
#   content = "{\"project\": \"${var.project_name}\", \"env\": \"${var.environment}\"}"
# }

resource "local_file" "readme" {
  filename = "/tmp/devops-lab/0E-03/output/README.md"
  content  = <<-EOT
    # ${var.project_name}

    Environment: ${var.environment}

    This README was generated by Terraform.
  EOT
}

output "config_json_path" {
  value       = local_file.config_json.filename
  description = "Path to the generated config.json"
}

output "readme_path" {
  value       = local_file.readme.filename
  description = "Path to the generated README.md"
}
EOF

# Write variables.tf
cat > "$WORK_DIR/variables.tf" << 'EOF'
variable "project_name" {
  description = "Project name"
  type        = string
  default     = "devops-lab"
}

variable "environment" {
  description = "Deployment environment"
  type        = string
  default     = "dev"
}
EOF

# Remove any previous student work files
rm -f "$WORK_DIR/plan-output.txt"
rm -f "$WORK_DIR/lifecycle-notes.txt"

# Run init and apply if tofu/terraform is available
if [[ -n "$TF_CMD" ]]; then
  echo ""
  echo "Running: $TF_CMD init"
  (cd "$WORK_DIR" && $TF_CMD init -upgrade 2>&1)

  echo ""
  echo "Running: $TF_CMD apply -auto-approve (establishing initial state)"
  (cd "$WORK_DIR" && $TF_CMD apply -auto-approve 2>&1)

  echo ""
  echo "Initial state established. Output files:"
  ls "$WORK_DIR/output/" 2>/dev/null
  echo ""
  cat "$WORK_DIR/output/config.json" 2>/dev/null && echo ""
else
  # No tofu/terraform — still set up .terraform mock structure so verify can check files
  echo ""
  echo "Warning: neither 'tofu' nor 'terraform' found."
  echo "The exercise files have been created, but you will need to install"
  echo "OpenTofu to run init/plan/apply/destroy."
  echo ""
  echo "Install OpenTofu:"
  echo "  curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh | sh -s -- --install-method standalone"
  echo ""
  echo "After installing, run this reset.sh again to set up initial state."
fi

echo ""
echo "Done. Your task:"
echo "  1. Edit $WORK_DIR/main.tf or variables.tf:"
echo "     - Change environment default from 'dev' to 'staging'"
echo "     - Add a third local_file resource named 'deployment_notes'"
echo "  2. Run: cd $WORK_DIR && $TF_CMD plan 2>&1 | tee $WORK_DIR/plan-output.txt"
echo "  3. Run: $TF_CMD apply -auto-approve"
echo "  4. Run: $TF_CMD destroy -auto-approve"
echo "  5. Write $WORK_DIR/lifecycle-notes.txt"
